config/routes.rb
Rails.application.routes.draw do
  resources :assign_employees
  get 'dashboard/index'
  get 'assign_employees/index'

  get 'employees/list'

  get 'clients/list'

  root 'login_page#login'
  get 'application/hello'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assign_employee.rb
class AssignEmployee < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/assign_employees_controller.rb
class AssignEmployeesController < ApplicationController
  before_action :set_assign_employee, only: [:show, :edit, :update, :destroy]

  # GET /assign_employees
  # GET /assign_employees.json
  def index
    @assign_employees = AssignEmployee.all
  end

  # GET /assign_employees/1
  # GET /assign_employees/1.json
  def show
  end

  # GET /assign_employees/new
  def new
    @assign_employee = AssignEmployee.new
  end

  # GET /assign_employees/1/edit
  def edit
  end

  # POST /assign_employees
  # POST /assign_employees.json
  def create
    @assign_employee = AssignEmployee.new(assign_employee_params)

    respond_to do |format|
      if @assign_employee.save
        format.html { redirect_to @assign_employee, notice: 'Assign employee was successfully created.' }
        format.json { render :show, status: :created, location: @assign_employee }
      else
        format.html { render :new }
        format.json { render json: @assign_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assign_employees/1
  # PATCH/PUT /assign_employees/1.json
  def update
    respond_to do |format|
      if @assign_employee.update(assign_employee_params)
        format.html { redirect_to @assign_employee, notice: 'Assign employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @assign_employee }
      else
        format.html { render :edit }
        format.json { render json: @assign_employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assign_employees/1
  # DELETE /assign_employees/1.json
  def destroy
    @assign_employee.destroy
    respond_to do |format|
      format.html { redirect_to assign_employees_url, notice: 'Assign employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assign_employee
      @assign_employee = AssignEmployee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assign_employee_params
      params.require(:assign_employee).permit(:client, :employee, :assign_date, :comments)
    end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  def list
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def list
  end
end

app/controllers/login_page_controller.rb
class LoginPageController < ApplicationController
  def login
  	 render :layout => 'login'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	 # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Alindal HR Pro "
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/assign_employees_helper.rb
module AssignEmployeesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/login_page_helper.rb
module LoginPageHelper
end

app/views/assign_employees/_form.html.erb
<%= form_for(assign_employee) do |f| %>
  <% if assign_employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assign_employee.errors.count, "error") %> prohibited this assign_employee from being saved:</h2>

      <ul>
      <% assign_employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :client %>
    <%= f.text_field :client %>
  </div>

  <div class="field">
    <%= f.label :employee %>
    <%= f.text_field :employee %>
  </div>

  <div class="field">
    <%= f.label :assign_date %>
    <%= f.date_select :assign_date %>
  </div>

  <div class="field">
    <%= f.label :comments %>
    <%= f.text_area :comments %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/assign_employees/edit.html.erb
<h1>Editing Assign Employee</h1>

<%= render 'form', assign_employee: @assign_employee %>

<%= link_to 'Show', @assign_employee %> |
<%= link_to 'Back', assign_employees_path %>

app/views/assign_employees/index.html.erb
<div class="row">
                    

                    <div class="col-lg-12">
                        <div class="card-box">

<p id="notice"><%= notice %></p>
                            

                            <h4 class="header-title m-t-0 m-b-30">Assigned Employees</h4>

                           <p><%= button_to 'Assign New Employee', new_assign_employee_path ,:class=>"btn btn-pink pull-right",:method => :get%></p>

                            <table class="table table table-hover m-0">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Company Name</th>
                                        <th>Client Name</th>
                                        <th>Assigned Date</th>
                                        <th>Comments</th>
                                        <th colspan="3">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                 <% @assign_employees.each do |assign_employee| %>
                                    <tr>
                                        <td><%= assign_employee.id %></td>
                                        <td><%= assign_employee.client %></td>
        <td><%= assign_employee.employee %></td>
        <td><%= assign_employee.assign_date %></td>
        <td><%= assign_employee.comments %></td>
        <td><%= button_to 'Show', assign_employee,:class=>"btn btn-primary",:method => :get %></td>
        <td><%= button_to 'Edit', edit_assign_employee_path(assign_employee) ,:class =>"btn btn-warning",:method => :get%></td>
      <td> <%= button_to 'Delete', assign_employee, method: :delete, data: { confirm: 'Are you sure?' } ,:class=>"btn btn-danger"%></td>
                                    </tr>
                                    <% end %>
                                </tbody>
                            </table>

                        </div>
                    </div><!-- end col -->

                </div>
                <!-- end row -->

app/views/assign_employees/new.html.erb
   <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box">
                            <div class="row">
                                

                                <div class="col-md-12">
                                    <h4 class="m-t-0 header-title"><b>Assign Employee</b></h4>
                                    <%= form_for @assign_employee, :html => {:class => "form-horizontal"} do |f| %>

                                   
                                     <div class="form-group">
								        <%= f.label :client, "Choose Client:", class: "col-sm-4 control-label" %>
								        <div class="col-sm-6">
								       <%= f.select :client, AssignEmployee.all.collect { |p| p.client }, include_blank: true ,:class =>'form-control' %>
								        </div>
								      </div>
								      <div class="form-group">
								        <%= f.label :employee, "Choose Employee:", class: "col-sm-4 control-label" %>
								        <div class="col-sm-6">
								       <%= f.select :employee, AssignEmployee.all.collect { |p| p.employee }, include_blank: true %>
								        </div>
								      </div>
                                       
                                        
                                        <div class="form-group">
                                         <%= f.label :assign_date,"Assign Date",class:"col-sm-4 control-label"%>
                                            
                                            <div class="col-sm-6">
                                            <%=date_select "post", "assign_date"%>
                                            
                                            </div>
                                        </div>
                                        <div class="form-group">
                                        <%= f.label :comments,"Comments",class:"col-sm-4 control-label"%>
                                           
                                            <div class="col-sm-6">
                                            <%= f.text_area :comments, :rows => 2,class:"form-control"%>
                                                
                                            </div>
                                        </div>
                                        
                                        <div class="form-group m-b-0">
                                            <div class="col-sm-offset-4 col-sm-6">
                                               <%= f.submit "Submit", class: "btn btn-default btn-primary" %>  
                                              <!-- <button type="submit" class="btn btn-info waves-effect waves-light">Assign</button> -->
                                            </div>
                                        </div>
                                     <%end%>
                                </div><!-- end col -->
                            </div><!-- end row -->
                        </div>
                    </div><!-- end col -->
                </div>
                <!-- end row -->
              
               

app/views/assign_employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Client:</strong>
  <%= @assign_employee.client %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @assign_employee.employee %>
</p>

<p>
  <strong>Assign date:</strong>
  <%= @assign_employee.assign_date %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @assign_employee.comments %>
</p>

<%= link_to 'Edit', edit_assign_employee_path(@assign_employee) %> |
<%= link_to 'Back', assign_employees_path %>

app/views/clients/list.html.erb
<h1>Clients#list</h1>
<p>Find me in app/views/clients/list.html.erb</p>

app/views/dashboard/index.html.erb
<!-- <h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>
 -->

app/views/employees/list.html.erb
<h1>Employees#list</h1>
<p>Find me in app/views/employees/list.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

      <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

  </head>

  <body>
   <!-- Navigation Bar-->
        <header id="topnav">
            <div class="topbar-main">
                <div class="container">

                    <!-- LOGO -->
                    <div class="topbar-left">
                        <a href="index.html" class="logo"><span>Admin<span>to</span></span></a>
                    </div>
                    <!-- End Logo container-->


                    <div class="menu-extras">

                        <ul class="nav navbar-nav navbar-right pull-right">
                            <li>
                                <form role="search" class="navbar-left app-search pull-left hidden-xs">
                                     <input type="text" placeholder="Search..." class="form-control">
                                     <a href=""><i class="fa fa-search"></i></a>
                                </form>
                            </li>
                            <li>
                                <!-- Notification -->
                                <div class="notification-box">
                                    <ul class="list-inline m-b-0">
                                        <li>
                                            <a href="javascript:void(0);" class="right-bar-toggle">
                                                <i class="zmdi zmdi-notifications-none"></i>
                                            </a>
                                            <div class="noti-dot">
                                                <span class="dot"></span>
                                                <span class="pulse"></span>
                                            </div>
                                        </li>
                                    </ul>
                                </div>
                                <!-- End Notification bar -->
                            </li>

                            <li class="dropdown user-box">
                                <a href="" class="dropdown-toggle waves-effect waves-light profile " data-toggle="dropdown" aria-expanded="true">
                                   <%= image_tag "users/avatar-1.jpg", :class => "img-circle user-img"%>

                                    <!-- <img src="" alt="user-img" class="img-circle user-img"> -->
                                    <div class="user-status away"><i class="zmdi zmdi-dot-circle"></i></div>
                                </a>

                                <ul class="dropdown-menu">
                                    <li><a href="javascript:void(0)"><i class="ti-user m-r-5"></i> Profile</a></li>
                                    <li><a href="javascript:void(0)"><i class="ti-settings m-r-5"></i> Settings</a></li>
                                    <li><a href="javascript:void(0)"><i class="ti-lock m-r-5"></i> Lock screen</a></li>
                                    <li><a href="javascript:void(0)"><i class="ti-power-off m-r-5"></i> Logout</a></li>
                                </ul>
                            </li>
                        </ul>
                        <div class="menu-item">
                            <!-- Mobile menu toggle-->
                            <a class="navbar-toggle">
                                <div class="lines">
                                    <span></span>
                                    <span></span>
                                    <span></span>
                                </div>
                            </a>
                            <!-- End mobile menu toggle-->
                        </div>
                    </div>

                </div>
            </div>

            <div class="navbar-custom">
                <div class="container">
                    <div id="navigation">
                        <!-- Navigation Menu-->
                        <ul class="navigation-menu">
                            <li class="active">
                                <a href="#" class="active"><i class="zmdi zmdi-view-dashboard"></i> <span> Dashboard </span> </a>
                            </li>
                            <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-invert-colors"></i> <span> Employee </span> </a>
                                <ul class="submenu megamenu">
                                    <li>
                                        <ul>
                                            <li><a href="">New Employee</a></li>
                                            <li><a href="">Manage Employee</a></li>
                                            <li><a href="">Payslip</a></li>
                                          
                                        </ul>
                                    </li>
                                    <!-- <li>
                                        <ul>
                                            <li><a href="ui-modals.html">Modals</a></li>
                                            <li><a href="ui-notification.html">Notification</a></li>
                                            <li><a href="ui-range-slider.html">Range Slider</a></li>
                                            <li><a href="ui-components.html">Components</a>
                                            <li><a href="ui-sweetalert.html">Sweet Alert</a>
                                            <li><a href="ui-treeview.html">Tree view</a>
                                            <li><a href="ui-widgets.html">Widgets</a></li>
                                        </ul>
                                    </li> -->
                                </ul>
                            </li>

                            <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-collection-text"></i><span> Client</span> </a>
                                <ul class="submenu">
                                    <li><a href="">New Client</a></li>
                                    <li><a href="">Manage Client</a></li>
                                    <li><a href="">Invoice</a></li>
                                  
                                </ul>
                            </li>

                            <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-view-list"></i> <span> Assign Employee</span> </a>
                                <ul class="submenu">
                                    <li><a href="/assign_employees/new">Assign New</a></li>
                                    <li><a href="/assign_employees/">List Assignees</a></li>
                                   
                                </ul>
                            </li>

                            <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-chart"></i><span> Settings </span> </a>
                                <!-- <ul class="submenu"> -->
                                   <!--  <li><a href="">Flot Chart</a></li>
                                    <li><a href="">Morris Chart</a></li>
                                    <li><a href="">Chartist Charts</a></li>
                                    <li><a href="">Chartjs Chart</a></li>
                                    <li><a href="chart-other.html">Other Chart</a></li> -->
                                <!-- </ul> -->
                            </li>

                           <!--  <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-collection-item"></i><span> Pages </span> </a>
                                <ul class="submenu">
                                    <li><a href="page-starter.html">Starter Page</a></li>
                                    <li><a href="page-login.html">Login</a></li>
                                    <li><a href="page-register.html">Register</a></li>
                                    <li><a href="page-recoverpw.html">Recover Password</a></li>
                                    <li><a href="page-lock-screen.html">Lock Screen</a></li>
                                    <li><a href="page-confirm-mail.html">Confirm Mail</a></li>
                                    <li><a href="page-404.html">Error 404</a></li>
                                    <li><a href="page-500.html">Error 500</a></li>
                                </ul>
                            </li> -->

                          <!--   <li class="has-submenu">
                                <a href="#"><i class="zmdi zmdi-layers"></i><span>Extra Pages </span> </a>
                                <ul class="submenu megamenu">
                                    <li>
                                        <ul>
                                            <li><a href="extras-projects.html">Projects</a></li>
                                            <li><a href="extras-tour.html">Tour</a></li>
                                            <li><a href="extras-taskboard.html">Taskboard</a></li>
                                            <li><a href="extras-inbox.html">Mail</a></li>
                                            <li><a href="extras-taskdetail.html">Task Detail</a></li>
                                            <li><a href="extras-maps.html">Maps</a></li>
                                            <li><a href="extras-calendar.html" >Calendar</a></li>
                                            <li><a href="extras-contact.html">Contact list</a></li>
                                            <li><a href="extras-pricing.html">Pricing</a></li>
                                        </ul>
                                    </li>
                                    <li>
                                        <ul>
                                            <li><a href="extras-timeline.html">Timeline</a></li>
                                            <li><a href="extras-invoice.html">Invoice</a></li>
                                            <li><a href="extras-profile.html">Profile</a></li>
                                            <li><a href="extras-faq.html">FAQ</a></li>
                                            <li><a href="extras-gallery.html">Gallery</a></li>
                                            <li><a href="extras-email-template.html">Email template</a></li>
                                            <li><a href="extras-maintenance.html">Maintenance</a></li>
                                            <li><a href="extras-comingsoon.html">Coming soon</a></li>
                                        </ul>
                                    </li>
                                </ul>
                            </li> -->

                        </ul>
                        <!-- End navigation menu  -->
                    </div>
                </div>
            </div>
        </header>
        <!-- End Navigation Bar-->
        <div class="wrapper">
            
    <%= yield %>
   
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login Alindal HR Pro </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/login_page/login.html.erb
<div class="account-pages"></div>
        <div class="clearfix"></div>
        <div class="wrapper-page">
            <div class="text-center">
                <a href="index.html" class="logo"><span>Admin<span>to</span></span></a>
                <h5 class="text-muted m-t-0 font-600">Responsive Admin Dashboard</h5>
            </div>
        	<div class="m-t-40 card-box">
                <div class="text-center">
                    <h4 class="text-uppercase font-bold m-b-0">Sign In</h4>
                </div>
                <div class="panel-body">
                    <form class="form-horizontal m-t-20" action="dashboard/index">

                        <div class="form-group ">
                            <div class="col-xs-12">
                                <input class="form-control" type="text" required="" placeholder="Username">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-xs-12">
                                <input class="form-control" type="password" required="" placeholder="Password">
                            </div>
                        </div>

                        <div class="form-group ">
                            <div class="col-xs-12">
                                <div class="checkbox checkbox-custom">
                                    <input id="checkbox-signup" type="checkbox">
                                    <label for="checkbox-signup">
                                        Remember me
                                    </label>
                                </div>

                            </div>
                        </div>

                        <div class="form-group text-center m-t-30">
                            <div class="col-xs-12">
                                <button class="btn btn-custom btn-bordred btn-block waves-effect waves-light" type="submit">Log In</button>
                            </div>
                        </div>

                        <div class="form-group m-t-30 m-b-0">
                            <div class="col-sm-12">
                                <a href="page-recoverpw.html" class="text-muted"><i class="fa fa-lock m-r-5"></i> Forgot your password?</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
            <!-- end card-box-->

            <div class="row">
                <div class="col-sm-12 text-center">
                    <p class="text-muted">Don't have an account? <a href="page-register.html" class="text-primary m-l-5"><b>Sign Up</b></a></p>
                </div>
            </div>
            
        </div>